### ISSUE TITLE
Cannot obtain submission Lock

### ISSUE THREAD

**Issue by CDaut** [kit-sdq/artemis4j#18]
When attempting to obtain a LockResult for grading, Optional#empty is returned although ungraded submissions are present. The following Code is used to obtain an AssesmentLock:
```[java]
    Optional<LockResult> assessmentLockWrapper;
    try {
      assessmentLockWrapper = ArtemisUtils
              .getArtemisClientInstance()
              .getAssessmentArtemisClient()
              .startNextAssessment(selectedExercise, 1); //assuming this function is used to get a Lock on a submission for grading
    } catch (ArtemisClientException e) {
      ArtemisUtils.displayGenericErrorBalloon(
              String.format(ERROR_NEXT_ASSESSMENT_FORMATTER, e.getMessage())
      );
      return;
    }
```
Locking a submission for grading using the web interface is possible.
[This](https://artemis-test.ipd.kit.edu/course-management/1/programming-exercises/18/scores) Exercise is used for testing.

**Comment by CDaut** [comment]
This might be because the test-tutor has no rights to grade the exercise and I cannot change the Password for my test account.

**Comment by CDaut** [comment]
Grading rounds are 0 indexed.

**Comment by dfuchss** [comment]
I think you start grading round two (Parameter: 1) :)
